### ISSUE TITLE
Create a view sorted only by submission time (or autoincrement) 

### ISSUE THREAD

**Issue by Grissess** [COSI-Lab/NodeTalks#13]
This would allow one to see which submissions, regardless of type, were submitted at "around" the same time :)

**Comment by lannonbr** [comment]
For now I am thinking for the quick implementation, I will create another page which goes to it. A fix that I'll look into in the future is to have a filter/search feature on the main page.

**Comment by lannonbr** [comment]
Done. See Commit 441caea
