### ISSUE TITLE
Use talks as a template for meeting minutes

### ISSUE THREAD

**Issue by Grissess** [COSI-Lab/NodeTalks#9]
Without changing the structure, the data in talks will be useful for creating a skeletal version of the meeting minutes recorded for a meeting.

**Comment by lannonbr** [comment]
With the API, specifically [this](http://talks.cosi.clarkson.edu/api/talks/visible), This likely can be done in an hour.

**Comment by lannonbr** [comment]
Initally completed with @fdb69bb
